import { useEffect, useState } from 'react';
import type { LucideIcon } from 'lucide-react';
import {
  Activity, ArrowDownLeft, ArrowUpLeft, Bell, Box, CalendarDays, Check,
  ChevronDown, ChevronLeft, CircleHelp, CreditCard, FileBarChart, LayoutDashboard,
  Menu, Moon, MoreHorizontal, Package, PanelRight, Plus, Search, Settings,
  ShieldCheck, ShoppingCart, Sun, TrendingUp, UserRound, Users, Wallet, X,
} from 'lucide-react';

type Page = 'dashboard' | 'users' | 'products' | 'reports' | 'settings';
type MenuItem = { id: Page; label: string; icon: LucideIcon; badge?: string };

type User = { name: string; email: string; role: string; status: 'فعال' | 'غیرفعال'; color: string };

const menuItems: MenuItem[] = [
  { id: 'dashboard', label: 'داشبورد', icon: LayoutDashboard },
  { id: 'users', label: 'کاربران', icon: Users, badge: '۱۲۴' },
  { id: 'products', label: 'محصولات', icon: Package },
  { id: 'reports', label: 'گزارش‌ها', icon: FileBarChart },
  { id: 'settings', label: 'تنظیمات', icon: Settings },
];

const users: User[] = [
  { name: 'سارا محمدی', email: 'sara.m@sample.ir', role: 'مدیر محتوا', status: 'فعال', color: 'bg-rose-100 text-rose-600' },
  { name: 'علی رضایی', email: 'ali.r@sample.ir', role: 'کاربر عادی', status: 'فعال', color: 'bg-blue-100 text-blue-600' },
  { name: 'نگار احمدی', email: 'negar.a@sample.ir', role: 'پشتیبانی', status: 'فعال', color: 'bg-amber-100 text-amber-600' },
  { name: 'محمد کریمی', email: 'mohammad.k@sample.ir', role: 'کاربر عادی', status: 'غیرفعال', color: 'bg-emerald-100 text-emerald-600' },
];

const activities = [
  { icon: ShoppingCart, title: 'سفارش جدید ثبت شد', text: 'سفارش #۱۲۴۸۹ توسط سارا محمدی', time: '۵ دقیقه پیش', tone: 'bg-brand-100 text-brand-700' },
  { icon: UserRound, title: 'کاربر جدید اضافه شد', text: 'علی رضایی به تیم شما پیوست', time: '۲۳ دقیقه پیش', tone: 'bg-secondary-100 text-secondary-700' },
  { icon: CreditCard, title: 'پرداخت موفق', text: 'پرداخت اشتراک حرفه‌ای دریافت شد', time: '۱ ساعت پیش', tone: 'bg-amber-100 text-amber-700' },
  { icon: ShieldCheck, title: 'گزارش امنیتی', text: 'ورود جدید از دستگاه ناشناس', time: '۳ ساعت پیش', tone: 'bg-rose-100 text-rose-700' },
];

function App() {
  const [page, setPage] = useState<Page>('dashboard');
  const [dark, setDark] = useState<boolean>(() => localStorage.getItem('admin-theme') === 'dark');
  const [sidebarOpen, setSidebarOpen] = useState<boolean>(false);
  const [notifications, setNotifications] = useState<boolean>(false);

  useEffect(() => {
    document.documentElement.classList.toggle('dark', dark);
    localStorage.setItem('admin-theme', dark ? 'dark' : 'light');
  }, [dark]);

  const pageTitle = menuItems.find((item) => item.id === page)?.label ?? 'داشبورد';
  const navigate = (nextPage: Page): void => { setPage(nextPage); setSidebarOpen(false); };

  return (
    <div dir="rtl" className="min-h-screen bg-[#f7f9fb] font-sans text-ink-900 transition-colors dark:bg-[#111b22] dark:text-white">
      <Sidebar activePage={page} open={sidebarOpen} onNavigate={navigate} onClose={() => setSidebarOpen(false)} />
      <main className="min-h-screen lg:mr-[272px]">
        <Header title={pageTitle} onMenu={() => setSidebarOpen(true)} dark={dark} onTheme={() => setDark(!dark)} notifications={notifications} onNotifications={() => setNotifications(!notifications)} />
        <div className="mx-auto max-w-[1440px] p-4 sm:p-6 lg:p-8">
          {page === 'dashboard' && <Dashboard onNavigate={navigate} />}
          {page === 'users' && <UsersPage />}
          {page === 'products' && <ProductsPage />}
          {page === 'reports' && <ReportsPage />}
          {page === 'settings' && <SettingsPage />}
        </div>
      </main>
    </div>
  );
}

function Sidebar({ activePage, open, onNavigate, onClose }: { activePage: Page; open: boolean; onNavigate: (page: Page) => void; onClose: () => void }) {
  return <>
    {open && <button aria-label="بستن منو" onClick={onClose} className="fixed inset-0 z-30 bg-ink-900/40 lg:hidden" />}
    <aside className={`fixed right-0 top-0 z-40 flex h-screen w-[272px] flex-col border-l border-ink-100 bg-white p-5 transition-transform dark:border-white/10 dark:bg-[#18252d] lg:translate-x-0 ${open ? 'translate-x-0' : 'translate-x-full'}`}>
      <div className="mb-10 flex items-center justify-between px-2">
        <div className="flex items-center gap-3">
          <div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-brand-600 text-white shadow-lg shadow-brand-600/20"><PanelRight size={23} /></div>
          <div><p className="text-[17px] font-extrabold tracking-tight">دیدبان</p><p className="text-[11px] text-ink-400">پنل مدیریت هوشمند</p></div>
        </div>
        <button onClick={onClose} className="icon-button lg:hidden"><X size={18} /></button>
      </div>
      <p className="mb-3 px-3 text-[11px] font-bold text-ink-400">منوی اصلی</p>
      <nav className="space-y-1.5">
        {menuItems.map(({ id, label, icon: Icon, badge }) => <button key={id} onClick={() => onNavigate(id)} className={`group flex w-full items-center gap-3 rounded-xl px-3.5 py-3 text-sm font-semibold transition ${activePage === id ? 'bg-brand-50 text-brand-700 dark:bg-brand-500/15 dark:text-brand-300' : 'text-ink-500 hover:bg-ink-50 hover:text-ink-800 dark:text-ink-300 dark:hover:bg-white/5 dark:hover:text-white'}`}><Icon size={19} strokeWidth={activePage === id ? 2.4 : 1.8} /><span className="flex-1 text-right">{label}</span>{badge && <span className="rounded-md bg-brand-100 px-2 py-0.5 text-[10px] text-brand-700 dark:bg-brand-500/20 dark:text-brand-300">{badge}</span>}{activePage === id && <ChevronLeft size={15} />}</button>)}
      </nav>
      <p className="mb-3 mt-9 px-3 text-[11px] font-bold text-ink-400">دسترسی سریع</p>
      <nav className="space-y-1.5">
        <button onClick={() => onNavigate('products')} className="flex w-full items-center gap-3 rounded-xl px-3.5 py-3 text-sm font-semibold text-ink-500 transition hover:bg-ink-50 hover:text-ink-800 dark:text-ink-300 dark:hover:bg-white/5"><Box size={19} /><span>موجودی انبار</span></button>
        <button onClick={() => onNavigate('reports')} className="flex w-full items-center gap-3 rounded-xl px-3.5 py-3 text-sm font-semibold text-ink-500 transition hover:bg-ink-50 hover:text-ink-800 dark:text-ink-300 dark:hover:bg-white/5"><Activity size={19} /><span>تحلیل عملکرد</span></button>
      </nav>
      <div className="mt-auto overflow-hidden rounded-2xl bg-ink-900 p-4 text-white dark:bg-brand-900">
        <div className="mb-3 flex h-9 w-9 items-center justify-center rounded-xl bg-brand-500/20 text-brand-300"><CircleHelp size={19} /></div>
        <p className="text-sm font-bold">به کمک نیاز دارید؟</p><p className="mt-1 text-[11px] leading-5 text-white/60">راهنمای کامل استفاده از پنل را ببینید.</p>
        <button className="mt-3 flex items-center gap-1 text-xs font-bold text-brand-300">مشاهده راهنما <ChevronLeft size={14} /></button>
      </div>
    </aside>
  </>;
}

function Header({ title, onMenu, dark, onTheme, notifications, onNotifications }: { title: string; onMenu: () => void; dark: boolean; onTheme: () => void; notifications: boolean; onNotifications: () => void }) {
  return <header className="sticky top-0 z-20 flex h-[82px] items-center justify-between border-b border-ink-100/80 bg-[#f7f9fb]/90 px-4 backdrop-blur-xl dark:border-white/10 dark:bg-[#111b22]/90 sm:px-6 lg:px-8">
    <div className="flex items-center gap-3"><button onClick={onMenu} className="icon-button lg:hidden"><Menu size={21} /></button><div><p className="text-xs text-ink-400">شنبه، ۲۴ شهریور ۱۴۰۳</p><h1 className="mt-0.5 text-xl font-extrabold sm:text-2xl">{title}</h1></div></div>
    <div className="flex items-center gap-1 sm:gap-3"><div className="relative hidden md:block"><Search className="absolute right-3 top-1/2 -translate-y-1/2 text-ink-400" size={17} /><input className="h-10 w-48 rounded-xl border-0 bg-white pr-10 text-xs shadow-sm outline-none placeholder:text-ink-400 focus:ring-2 focus:ring-brand-500/20 dark:bg-white/5 sm:w-64" placeholder="جستجو در پنل..." /></div><button onClick={onTheme} className="icon-button" aria-label="تغییر حالت نمایش">{dark ? <Sun size={19} /> : <Moon size={19} />}</button><div className="relative"><button onClick={onNotifications} className="icon-button" aria-label="اعلان‌ها"><Bell size={19} /><span className="absolute right-2 top-2 h-1.5 w-1.5 rounded-full bg-rose-500 ring-2 ring-[#f7f9fb] dark:ring-[#111b22]" /></button>{notifications && <div className="absolute left-0 top-12 w-64 rounded-2xl border border-ink-100 bg-white p-4 shadow-float dark:border-white/10 dark:bg-[#18252d]"><p className="text-sm font-bold">اعلان‌ها</p><p className="mt-2 text-xs leading-6 text-ink-500 dark:text-ink-300">۳ اعلان جدید برای بررسی وجود دارد.</p></div>}</div><div className="mr-1 hidden h-9 w-px bg-ink-200 dark:bg-white/10 sm:block" /><button className="flex items-center gap-2 rounded-xl p-1.5 transition hover:bg-white dark:hover:bg-white/5"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-secondary-100 text-xs font-extrabold text-secondary-700">س‌م</div><div className="hidden text-right sm:block"><p className="text-xs font-bold">سارا محمدی</p><p className="text-[10px] text-ink-400">مدیر سیستم</p></div><ChevronDown size={15} className="hidden text-ink-400 sm:block" /></button></div>
  </header>;
}

function Dashboard({ onNavigate }: { onNavigate: (page: Page) => void }) {
  return <div className="space-y-6"><section className="relative overflow-hidden rounded-3xl bg-gradient-to-l from-ink-900 via-ink-800 to-brand-900 p-6 text-white shadow-float sm:p-8"><div className="relative z-10 max-w-xl"><div className="mb-4 inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/10 px-3 py-1.5 text-[11px] text-brand-200"><span className="h-1.5 w-1.5 rounded-full bg-brand-300" /> وضعیت سیستم: پایدار</div><h2 className="text-2xl font-extrabold leading-[1.5] sm:text-3xl">سلام سارا،<br /><span className="text-brand-300">روز خوبی برای رشد کسب‌وکار است.</span></h2><p className="mt-3 max-w-md text-sm leading-7 text-white/60">اینجا تصویری واضح از عملکرد امروز و مسیر پیش‌روی شماست.</p><button onClick={() => onNavigate('reports')} className="mt-6 inline-flex items-center gap-2 rounded-xl bg-white px-4 py-2.5 text-xs font-bold text-ink-900 transition hover:bg-brand-50">مشاهده گزارش کامل <ChevronLeft size={16} /></button></div><div className="absolute -left-12 -top-20 h-72 w-72 rounded-full border border-white/10" /><div className="absolute -left-1 top-6 h-52 w-52 rounded-full border border-white/5" /><TrendingUp className="absolute bottom-7 left-10 hidden text-white/10 sm:block" size={140} /></section><StatsGrid /><div className="grid gap-6 xl:grid-cols-[1.5fr_1fr]"><SalesChart /><ActivityCard /></div><div className="grid gap-6 xl:grid-cols-[1.4fr_1fr]"><UsersCard onNavigate={onNavigate} /><QuickActions onNavigate={onNavigate} /></div></div>;
}

function StatsGrid() {
  const stats = [{ label: 'فروش کل', value: '۲۴۸,۵۰۰,۰۰۰', unit: 'تومان', change: '+۱۲.۸٪', icon: Wallet, tone: 'bg-brand-50 text-brand-600 dark:bg-brand-500/15 dark:text-brand-300', up: true }, { label: 'تعداد سفارش‌ها', value: '۱,۲۴۸', unit: 'سفارش', change: '+۸.۲٪', icon: ShoppingCart, tone: 'bg-secondary-50 text-secondary-600 dark:bg-secondary-500/15 dark:text-secondary-300', up: true }, { label: 'کاربران جدید', value: '۳,۵۶۴', unit: 'نفر', change: '+۱۸.۴٪', icon: Users, tone: 'bg-amber-50 text-amber-600 dark:bg-amber-500/15 dark:text-amber-300', up: true }, { label: 'نرخ تبدیل', value: '۶.۸٪', unit: 'از بازدید', change: '-۲.۱٪', icon: TrendingUp, tone: 'bg-rose-50 text-rose-600 dark:bg-rose-500/15 dark:text-rose-300', up: false }];
  return <div className="grid grid-cols-2 gap-4 xl:grid-cols-4">{stats.map(({ label, value, unit, change, icon: Icon, tone, up }) => <div key={label} className="surface p-4 sm:p-5"><div className="flex items-start justify-between"><div className={`flex h-10 w-10 items-center justify-center rounded-xl ${tone}`}><Icon size={19} /></div><span className={`flex items-center gap-0.5 rounded-md px-1.5 py-1 text-[10px] font-bold ${up ? 'bg-brand-50 text-brand-700 dark:bg-brand-500/10 dark:text-brand-300' : 'bg-rose-50 text-rose-600 dark:bg-rose-500/10 dark:text-rose-300'}`}>{up ? <ArrowUpLeft size={12} /> : <ArrowDownLeft size={12} />}{change}</span></div><p className="mt-4 text-xs text-ink-500 dark:text-ink-300">{label}</p><p className="mt-1 text-xl font-extrabold tracking-tight sm:text-2xl">{value}<span className="mr-1 text-[10px] font-medium text-ink-400">{unit}</span></p></div>)}</div>;
}

function SalesChart() { const bars = [42, 58, 48, 72, 63, 85, 76, 92, 68, 80, 95, 88]; return <section className="surface p-5 sm:p-6"><div className="flex items-center justify-between"><div><h3 className="font-extrabold">گزارش فروش</h3><p className="mt-1 text-xs text-ink-400">مجموع فروش در ۱۲ ماه گذشته</p></div><select className="rounded-lg border border-ink-100 bg-ink-50 px-2 py-2 text-[11px] text-ink-600 outline-none dark:border-white/10 dark:bg-white/5 dark:text-ink-200"><option>امسال</option><option>سال گذشته</option></select></div><div className="mt-7 flex h-52 items-end gap-2 sm:gap-4">{bars.map((height, index) => <div key={index} className="group flex h-full flex-1 flex-col items-center justify-end gap-2"><div className="relative w-full max-w-8 rounded-t-lg bg-ink-100 transition-all duration-300 group-hover:bg-brand-200 dark:bg-white/10 dark:group-hover:bg-brand-500/40" style={{ height: `${height}%` }}><div className="absolute inset-x-0 bottom-0 rounded-t-lg bg-brand-500/80" style={{ height: `${index % 3 === 0 ? '65%' : index % 4 === 0 ? '45%' : '28%'}` }} /></div><span className="text-[9px] text-ink-400">{['فر', 'اس', 'خرد', 'تیر', 'مرد', 'شه', 'مهر', 'آبا', 'آذر', 'دی', 'بهم', 'اسف'][index]}</span></div>)}</div></section>; }

function ActivityCard() { return <section className="surface p-5 sm:p-6"><div className="flex items-center justify-between"><h3 className="font-extrabold">فعالیت‌های اخیر</h3><button className="text-xs font-bold text-brand-600 dark:text-brand-300">مشاهده همه</button></div><div className="mt-5 space-y-4">{activities.map(({ icon: Icon, title, text, time, tone }) => <div key={title} className="flex items-start gap-3"><div className={`mt-0.5 flex h-9 w-9 shrink-0 items-center justify-center rounded-xl ${tone}`}><Icon size={16} /></div><div className="min-w-0 flex-1"><p className="text-xs font-bold">{title}</p><p className="mt-1 truncate text-[11px] text-ink-500 dark:text-ink-300">{text}</p></div><span className="whitespace-nowrap text-[10px] text-ink-400">{time}</span></div>)}</div></section>; }

function UsersCard({ onNavigate }: { onNavigate: (page: Page) => void }) { return <section className="surface overflow-hidden"><div className="flex items-center justify-between p-5 sm:p-6"><div><h3 className="font-extrabold">کاربران جدید</h3><p className="mt-1 text-xs text-ink-400">آخرین اعضای ثبت‌نام شده</p></div><button onClick={() => onNavigate('users')} className="text-xs font-bold text-brand-600 dark:text-brand-300">مشاهده همه</button></div><div className="overflow-x-auto"><table className="w-full min-w-[500px] text-right text-xs"><thead className="border-y border-ink-100 bg-ink-50 text-[10px] text-ink-400 dark:border-white/10 dark:bg-white/5"><tr><th className="px-6 py-3 font-medium">کاربر</th><th className="px-4 py-3 font-medium">نقش</th><th className="px-4 py-3 font-medium">وضعیت</th><th className="px-6 py-3 font-medium">عملیات</th></tr></thead><tbody>{users.slice(0, 3).map((user) => <tr key={user.email} className="border-b border-ink-100 last:border-0 dark:border-white/10"><td className="px-6 py-3"><div className="flex items-center gap-3"><div className={`flex h-8 w-8 items-center justify-center rounded-lg text-[10px] font-bold ${user.color}`}>{user.name.slice(0, 1)}</div><div><p className="font-bold">{user.name}</p><p className="mt-0.5 text-[10px] text-ink-400">{user.email}</p></div></div></td><td className="px-4 py-3 text-ink-500 dark:text-ink-300">{user.role}</td><td className="px-4 py-3"><span className="rounded-md bg-brand-50 px-2 py-1 text-[10px] font-bold text-brand-700 dark:bg-brand-500/10 dark:text-brand-300">{user.status}</span></td><td className="px-6 py-3"><button className="icon-button h-8 w-8"><MoreHorizontal size={16} /></button></td></tr>)}</tbody></table></div></section>; }

function QuickActions({ onNavigate }: { onNavigate: (page: Page) => void }) { return <section className="surface p-5 sm:p-6"><div className="flex items-center justify-between"><div><h3 className="font-extrabold">دسترسی سریع</h3><p className="mt-1 text-xs text-ink-400">کارهای پرکاربرد خود را سریع انجام دهید</p></div><Plus size={18} className="text-brand-600" /></div><div className="mt-5 grid grid-cols-2 gap-3">{[{ label: 'افزودن محصول', icon: Package, page: 'products' as Page }, { label: 'دعوت کاربر', icon: Users, page: 'users' as Page }, { label: 'گزارش جدید', icon: FileBarChart, page: 'reports' as Page }, { label: 'تنظیمات پنل', icon: Settings, page: 'settings' as Page }].map(({ label, icon: Icon, page }) => <button key={label} onClick={() => onNavigate(page)} className="flex items-center gap-2.5 rounded-xl border border-ink-100 p-3 text-right text-xs font-bold text-ink-600 transition hover:border-brand-200 hover:bg-brand-50 hover:text-brand-700 dark:border-white/10 dark:text-ink-200 dark:hover:border-brand-500/30 dark:hover:bg-brand-500/10"><Icon size={17} className="text-brand-600" />{label}</button>)}</div></section>; }

function PageHeading({ title, description, action }: { title: string; description: string; action?: string }) { return <div className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm text-ink-400">مدیریت و کنترل</p><h2 className="mt-1 text-2xl font-extrabold">{title}</h2><p className="mt-2 text-xs text-ink-500 dark:text-ink-300">{description}</p></div>{action && <button className="inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-brand-600 px-4 text-xs font-bold text-white transition hover:bg-brand-700"><Plus size={16} />{action}</button>}</div>; }

function UsersPage() { return <div><PageHeading title="کاربران" description="اعضا، نقش‌ها و دسترسی‌های تیم خود را مدیریت کنید." action="افزودن کاربر" /><div className="surface overflow-hidden"><div className="flex flex-col gap-3 border-b border-ink-100 p-5 dark:border-white/10 sm:flex-row sm:items-center sm:justify-between"><div className="relative max-w-xs"><Search className="absolute right-3 top-1/2 -translate-y-1/2 text-ink-400" size={16} /><input className="input pr-9" placeholder="جستجوی کاربر..." /></div><div className="flex gap-2"><button className="rounded-xl bg-brand-50 px-3 py-2 text-xs font-bold text-brand-700 dark:bg-brand-500/10 dark:text-brand-300">همه کاربران</button><button className="rounded-xl px-3 py-2 text-xs font-bold text-ink-500 hover:bg-ink-50 dark:text-ink-300 dark:hover:bg-white/5">فعال</button></div></div><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-right text-xs"><thead className="bg-ink-50 text-[10px] text-ink-400 dark:bg-white/5"><tr><th className="px-6 py-4 font-medium">کاربر</th><th className="px-4 py-4 font-medium">نقش</th><th className="px-4 py-4 font-medium">وضعیت</th><th className="px-4 py-4 font-medium">آخرین فعالیت</th><th className="px-6 py-4 font-medium">عملیات</th></tr></thead><tbody>{users.map((user, index) => <tr key={user.email} className="border-t border-ink-100 dark:border-white/10"><td className="px-6 py-4"><div className="flex items-center gap-3"><div className={`flex h-9 w-9 items-center justify-center rounded-xl text-xs font-bold ${user.color}`}>{user.name.slice(0, 1)}</div><div><p className="font-bold">{user.name}</p><p className="mt-1 text-[10px] text-ink-400">{user.email}</p></div></div></td><td className="px-4 py-4 text-ink-500 dark:text-ink-300">{user.role}</td><td className="px-4 py-4"><span className={`rounded-md px-2 py-1 text-[10px] font-bold ${user.status === 'فعال' ? 'bg-brand-50 text-brand-700 dark:bg-brand-500/10 dark:text-brand-300' : 'bg-ink-100 text-ink-500 dark:bg-white/10 dark:text-ink-300'}`}>{user.status}</span></td><td className="px-4 py-4 text-ink-500 dark:text-ink-300">{index === 0 ? 'همین حالا' : `${index + 1} ساعت پیش`}</td><td className="px-6 py-4"><button className="icon-button h-8 w-8"><MoreHorizontal size={16} /></button></td></tr>)}</tbody></table></div><div className="flex items-center justify-between border-t border-ink-100 p-4 text-[11px] text-ink-400 dark:border-white/10"><span>نمایش ۱ تا ۴ از ۱۲۴ کاربر</span><div className="flex gap-1"><button className="icon-button h-8 w-8"><ChevronLeft size={15} /></button><button className="h-8 w-8 rounded-lg bg-brand-600 text-xs font-bold text-white">۱</button><button className="h-8 w-8 rounded-lg text-xs font-bold hover:bg-ink-50 dark:hover:bg-white/5">۲</button><button className="icon-button h-8 w-8"><ChevronLeft size={15} className="rotate-180" /></button></div></div></div></div>; }

function ProductsPage() { const products = [{ name: 'اشتراک حرفه‌ای', code: 'PRO-2024', price: '۲,۴۹۰,۰۰۰', stock: '۴۸' }, { name: 'اشتراک پایه', code: 'BAS-2024', price: '۸۹۰,۰۰۰', stock: '۱۲۶' }, { name: 'بسته سازمانی', code: 'ORG-2024', price: '۶,۹۰۰,۰۰۰', stock: '۲۳' }]; return <div><PageHeading title="محصولات" description="محصولات و موجودی قابل فروش خود را مدیریت کنید." action="افزودن محصول" /><div className="grid gap-4 md:grid-cols-3">{products.map((product, index) => <div key={product.code} className="surface p-5 transition hover:-translate-y-1 hover:shadow-float"><div className={`mb-5 flex h-12 w-12 items-center justify-center rounded-2xl ${index === 0 ? 'bg-brand-100 text-brand-700' : index === 1 ? 'bg-secondary-100 text-secondary-700' : 'bg-amber-100 text-amber-700'}`}><Package size={22} /></div><p className="text-base font-extrabold">{product.name}</p><p className="mt-1 text-[11px] text-ink-400">کد محصول: {product.code}</p><div className="mt-5 flex items-end justify-between"><div><p className="text-[10px] text-ink-400">قیمت</p><p className="mt-1 text-lg font-extrabold">{product.price}<span className="mr-1 text-[10px] text-ink-400">تومان</span></p></div><div className="text-left"><p className="text-[10px] text-ink-400">موجودی</p><p className="mt-1 text-sm font-bold text-brand-600">{product.stock} عدد</p></div></div><button className="mt-5 w-full rounded-xl border border-ink-100 py-2.5 text-xs font-bold text-ink-600 transition hover:border-brand-200 hover:bg-brand-50 hover:text-brand-700 dark:border-white/10 dark:text-ink-200 dark:hover:bg-brand-500/10">مدیریت محصول</button></div>)}</div></div>; }

function ReportsPage() { return <div><PageHeading title="گزارش‌ها" description="عملکرد کسب‌وکار را با گزارش‌های دقیق بررسی کنید." /><div className="grid gap-6 lg:grid-cols-2"><div className="surface p-6"><div className="flex items-center justify-between"><div><h3 className="font-extrabold">خلاصه عملکرد</h3><p className="mt-1 text-xs text-ink-400">این ماه در مقایسه با ماه قبل</p></div><CalendarDays className="text-brand-600" size={20} /></div><div className="mt-6 space-y-5">{[['درآمد ماهانه', '۸۶٪', 'bg-brand-500'], ['رضایت کاربران', '۹۲٪', 'bg-secondary-500'], ['تحویل سفارش‌ها', '۷۴٪', 'bg-amber-400']].map(([label, value, color]) => <div key={label}><div className="mb-2 flex justify-between text-xs"><span className="font-bold">{label}</span><span className="text-ink-400">{value}</span></div><div className="h-2 overflow-hidden rounded-full bg-ink-100 dark:bg-white/10"><div className={`h-full rounded-full ${color}`} style={{ width: value }} /></div></div>)}</div></div><div className="surface p-6"><h3 className="font-extrabold">گزارش‌های آماده</h3><div className="mt-5 space-y-3">{['گزارش فروش شهریور', 'تحلیل رفتار کاربران', 'گزارش موجودی انبار', 'خلاصه مالی فصل'].map((label, index) => <button key={label} className="flex w-full items-center gap-3 rounded-xl border border-ink-100 p-3 text-right transition hover:border-brand-200 hover:bg-brand-50 dark:border-white/10 dark:hover:bg-brand-500/10"><div className="flex h-9 w-9 items-center justify-center rounded-lg bg-brand-50 text-brand-600 dark:bg-brand-500/10 dark:text-brand-300"><FileBarChart size={17} /></div><div className="flex-1"><p className="text-xs font-bold">{label}</p><p className="mt-1 text-[10px] text-ink-400">به‌روزرسانی {index + 1} روز پیش</p></div><ChevronLeft size={15} className="text-ink-400" /></button>)}</div></div></div></div>; }

function SettingsPage() { const [saved, setSaved] = useState<boolean>(false); return <div><PageHeading title="تنظیمات" description="اطلاعات حساب و تنظیمات عمومی پنل را شخصی‌سازی کنید." /><div className="grid gap-6 lg:grid-cols-[220px_1fr]"><div className="surface h-fit p-2"><button className="flex w-full items-center gap-3 rounded-xl bg-brand-50 px-3 py-3 text-xs font-bold text-brand-700 dark:bg-brand-500/10 dark:text-brand-300"><Settings size={17} />عمومی</button><button className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-xs font-bold text-ink-500 hover:bg-ink-50 dark:text-ink-300 dark:hover:bg-white/5"><UserRound size={17} />حساب کاربری</button><button className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-xs font-bold text-ink-500 hover:bg-ink-50 dark:text-ink-300 dark:hover:bg-white/5"><Bell size={17} />اعلان‌ها</button></div><div className="surface p-5 sm:p-7"><div className="border-b border-ink-100 pb-5 dark:border-white/10"><h3 className="font-extrabold">اطلاعات عمومی</h3><p className="mt-1 text-xs text-ink-400">اطلاعات اصلی کسب‌وکار خود را ویرایش کنید.</p></div><div className="mt-6 grid gap-5 sm:grid-cols-2"><label className="text-xs font-bold">نام مجموعه<input className="input mt-2" defaultValue="استودیو دیدبان" /></label><label className="text-xs font-bold">ایمیل پشتیبانی<input className="input mt-2" defaultValue="support@didban.ir" /></label><label className="text-xs font-bold">شماره تماس<input className="input mt-2" defaultValue="۰۲۱-۸۸۷۷۶۶۵۵" /></label><label className="text-xs font-bold">منطقه زمانی<select className="input mt-2"><option>تهران (GMT+03:30)</option><option>استانبول (GMT+03:00)</option></select></label></div><div className="mt-7 flex items-center justify-between border-t border-ink-100 pt-5 dark:border-white/10"><span className={`text-xs font-bold text-brand-600 transition ${saved ? 'opacity-100' : 'opacity-0'}`}><Check size={15} className="ml-1 inline" />تغییرات ذخیره شد</span><button onClick={() => setSaved(true)} className="rounded-xl bg-brand-600 px-5 py-2.5 text-xs font-bold text-white transition hover:bg-brand-700">ذخیره تغییرات</button></div></div></div></div>; }

export default App;
